"""manual_upgrade_graph_to_longblob

Revision ID: 157edda0906c
Revises: e20f628efe48
Create Date: 2026-06-19 18:03:29.074978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '157edda0906c'
down_revision: Union[str, Sequence[str], None] = 'e20f628efe48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 🚀 Manually command the database to alter the column type to LONGBLOB
    op.alter_column(
        'graphjob', 
        'generated_graph',
        type_=mysql.LONGBLOB(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'graphjob', 
        'generated_graph',
        type_=mysql.BLOB(),
        existing_nullable=True
    )
    # ### end Alembic commands ###
